import { ThemeProvider } from "@/components/theme-provider";
import { Geist, Geist_Mono , Roboto, SUSE, Montserrat} from "next/font/google";

import "./globals.css";


const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto', // optional CSS variable
});

const suse = SUSE({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-suse',
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-montserrat',
});
  
export const metadata = {
  title: "CareerAdvisor",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      
      <body
        className={`antialiased overflow-x-hidden ${suse.className} `}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
